### ISSUE TITLE
Fatal Error while CreatingAll under Ubuntu 15.10

### ISSUE THREAD

**Issue by RGassmann** [podonoghue/usbdm-eclipse-makefiles-build#1]
After trying to install the deb file from sourceforge I ended up getting a Dependency not satisfiable: libwxgtk3.0-0 (Ubuntu 15.10 uses libwxgtk3.0-0v5).

So I tried to compile the source. Unfortunately I ran into a compiling error at the usbm-tcl
@ Building usbdm-tcl
src/UsbdmTclInterpreterImp.cpp:33:17: fatal error: tcl.h: no such file or directory

it would be great if you'd add the tcl.h file to your git and upload it. Thanks.

**Comment by podonoghue** [comment]
Hi Roman,

The TCL.h file is part of TCL so is not provided with USBDM.

Please make sure you have all the build dependencies given in
https://github.com/podonoghue/usbdm-eclipse-makefiles-build/blob/master/LinuxPackages

bye

**Comment by RGassmann** [comment]
Hi podonoghue,

got it to work. Because of the quotation marks around tcl.h I thought of 
tcl.h as a local file and not the tcl-dev file (actually if the tcl.h 
had been in <> I would have made the link to tcl). So... sorry for 
bothering you with such a silly question.
I now dug futher and although I ran your LinuxPackages script I had to 
find out, that the tcl could not be installed.
I guess I was hurrying at checking for errors the first time 
(unfortunately the script does not inform about errors at the end).
So Ubuntu 15.10 updated the tcl to 8.6 so after installing tcl8.6 (and 
of course its dev) I was finally able to compile the source.
Unfortunately after building the the Deb-File I couldn't install it 
since again the Dependency libwxgtk3.0-0 could not be satisfied.
After a little while I ran into the control.amd64, control.i386 
respectively, files where the dependencies for the packages are stated.
So after checking my system installation (I also installed Codeblocks 
which updated the wxgkt-libs to version 3.0.2+dfsg) I could reconfigure 
the dependencies from
libwxgtk3.0-0, libwxbase3.0-0, libgcc1, libstdc++6, libxerces-c3.1, 
libc6, libtcl8.5, libusb-1.0-0 to
libwxgtk3.0-0v5 (>= 3.0.2+dfsg), libwxbase3.0-0v5(>= 3.0.2+dfsg), 
libgcc1, libstdc++6, libxerces-c3.1, libc6, libtcl8.6, libusb-1.0-0
with this my deb-File-Dependencies were finally satisfied and I could 
install USBDM.
Finally I can program my uc's again :-).
Maybe you can use some of my noobish findings in the future.
Thanks again for your help.

Regards
Roman

Am 25.10.2015 um 22:15 schrieb podonoghue:
