### ISSUE TITLE
UsbdmFlashProgrammer 

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-eclipse-makefiles-build#14]
version 262 with target HCS12 unable to program the mc9s12g16 and g32 devices (internal error 119) (g48 and up is ok, except the G240 which is can't be masserase)

using version 220 with same hardware (using 262 firmware on the JS hardware) and same hex file works fine.

I compilling the source myself on linux, also checked with the released .deb files.
what can I  test, how can I solve this ? any debug messages ?

**Comment by HondaRulez** [comment]
Hi Again,

Since I upgraded my distro to debian buster I can't use the old version (230) due the dependency problems.
So I figured out what is the problem with the S9S12G16, G32, VR48 and VR64 devices and the latest usbdm version.

The Flash-programmer wants to load the *HCS12-*-flash-program.s19" files to the address 0x3000 (this is the target address in the  files.
on the low memory devices this is unexistent RAM location, so the load fails.

I just added a dirty trick to the flasprogrammmer source to bypass the checks, fortunatelly the loader is relocatable :)
the solution is should compile the *HCS12-*-flash-program.s19" files to address 0x3C00, that address exists on all these devices.

The datalogs and the "trick" are attached.

![usbdm_dirty_trick](https://user-images.githubusercontent.com/12637942/128775686-5a694295-3d90-4242-b1e1-d64c33ba9e1b.png)
[prog_log_hcs12_failed.zip](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/6957559/prog_log_hcs12_failed.zip)
[prog_log_hcs12_success.zip](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/6957560/prog_log_hcs12_success.zip)

**Comment by podonoghue** [comment]
Hi,
That is definitely a hack :).
Try this instead:

```
   // Find RAM region to use
   if (!device->getRamRegionFor(loadAddress, ramStart, ramEnd)) {
      log.warning("Failed to locate RAM region nominated in image\nUsing largest region available instead");
      device->getLargestRamRegion(ramStart, ramEnd);
   }
   log.print("Using RAM region [0x%8X..0x%8X]\n", ramStart, ramEnd);

```
This will fail later if the image is not relocatable.
bye
