### ISSUE TITLE
Using GDB with HCS12?

### ISSUE THREAD

**Issue by tadeokondrak** [podonoghue/usbdm-eclipse-makefiles-build#22]
I'm using USBDM with the MC9S12XDP512 (HCS12) for a course, and debugging with CodeWarrior is working.

I noticed that there's also a GDB server included as part of the USBDM tools, but it only supports some targets. Is this a technical limitation, or would it just be a matter of adapting the GDB server code from the other targets to work with HCS12?

Apologies if this isn't the right place to ask this.

**Comment by podonoghue** [comment]
Hi,

It would be possible to create a HCS12 GDB server but this has not been considered as I am unaware of a version of GDB targeted to the HCS12.
The main purpose of the GDB servers for Coldfire and ARM were to support use with Eclipse.
If you know of a GCC based toolchain for HCS12 I will consider this but there are other issues - I no longer use windows so development is a bit limited.

bye

**Comment by tadeokondrak** [comment]
I see, thank you for the answer. I didn't think about GDB/GCC not supporting it.
