### ISSUE TITLE
The latest updates can't be compille on Debian 10

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-eclipse-makefiles-build#24]
/usr/bin/ld: UsbdmFlashProgrammer.x86_64-linux-gnu/AppSettings.o: in function `AppSettings::openFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*) const':
/usr/include/c++/8/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: /usr/include/c++/8/bits/fs_path.h:380: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
/usr/bin/ld: UsbdmFlashProgrammer.x86_64-linux-gnu/AppSettings.o: in function `AppSettings::openFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*) const [clone .constprop.69]':
/usr/include/c++/8/bits/fs_path.h:184: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: /usr/include/c++/8/bits/fs_path.h:380: undefined reference to `std::filesystem::__cxx11::path::has_root_directory() const'
collect2: error: ld returned 1 exit status
make[2]: *** [Target.mk:106: UsbdmFlashProgrammer.x86_64-linux-gnu/UsbdmFlashProgrammer] Error 1
make[2]: Leaving directory '/opt/src/usbdm/usbdm-eclipse-makefiles-build/Programmer'
make[1]: *** [Makefile-x64.mk:11: UsbdmFlashProgrammer] Error 2
make[1]: Leaving directory '/opt/src/usbdm/usbdm-eclipse-makefiles-build/Programmer'
make: *** [Makefile-x64.mk:59: build-Programmer] Error 2
64-bit Make failed

**Comment by podonoghue** [comment]
This appears to be similar to this issue:
https://github.com/avast/retdec/issues/842

Can you check what version of GCC you have?
I'll look at this properly in a short while.
I am building on Mint.

bye

**Comment by HondaRulez** [comment]
fmiku@Dell-i7:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by podonoghue** [comment]
Hi,
I'm using : gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
This is a considerably later version.  It is probably because, being lazy, I am using some of the latest C++ features.  The file path handling is much nicer.  I'll see if I can do it in an earlier fashion.

**Comment by podonoghue** [comment]
I have changed some files to remove use of filesystem::path.  See if this fixes it otherwise is it possible to update to a later version of gcc?
bye

**Comment by HondaRulez** [comment]
this is the latest what the system update offers, I would not use any trick to install newer gcc because this is my daily machine too. Due the random freezes of the latest debian I avoiding yet the system update.

> Hi, I'm using : gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) This is a considerably later version. It is probably because, being lazy, I am using some of the latest C++ features. The file path handling is much nicer. I'll see if I can do it in an earlier fashion.

**Comment by HondaRulez** [comment]
With this mods compilled sucesfully. I just try to use..

Thx :)

> I have changed some files to remove use of filesystem::path. See if this fixes it otherwise is it possible to update to a later version of gcc? bye

**Comment by podonoghue** [comment]
Assumed Closed
