### ISSUE TITLE
Failed to detect/program some HCS12 devices.

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-eclipse-makefiles-build#27]
Hello,

I have problem with detect/program the S12VR48/64 devices.
The reason is have BAD IDs in the hcs12_devices.xml file.
The .diff file for the solution is attached.

![usbdm-vr-id](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/assets/12637942/c24270e5-39e3-4acf-beb8-d2a968e286d4)

![image_2023-11-25_131831924](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/assets/12637942/b9682441-c943-4d5c-a294-9cecc43a7420)

[hcs12_devices.xml.diff.gz](https://github.com/podonoghue/usbdm-eclipse-makefiles-build/files/13464100/hcs12_devices.xml.diff.gz)

Also have problem with programming S12GN16 devices (internal error), when set the device to S12GN32 the hex file sucessfully loaded and works as expected.

note: 
please update the Make and  .deb controll files to work with newer distros (some package names been changed..)

Thanks,

**Comment by podonoghue** [comment]
The hcs12_devices.xml have been updated.
I'm unlikely to do the other changes as it works on my system and I'm not an expert (more likely to break than fix!)
I'm using Mint so it isn't cutting edge.
I have no idea why the S12GN16 selection would fail as the only difference is the memory ranges.  The specs look correct.
I do not have a suitable chip to test with.

bye
