### ISSUE TITLE
Missing SingletonPluginFactory_Linux.h

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-eclipse-makefiles-build#3]
When compiling under Linux the following error occured:

In file included from ../Shared_V4/src/UsbdmTclInterpreterFactory.h:31:0,
                 from src/UsbdmTclInterpreterImp.cpp:42:
../Shared_V4/src/SingletonPluginFactory.h:52:42: fatal error: SingletonPluginFactory_Linux.h: Nincs ilyen fájl vagy könyvtár
compilation terminated.

**Comment by podonoghue** [comment]
Hi HondaRulez,

The Linux version tend to get out of date wrt windows where I do most development.
I have updated the files to build on Linux (Mint).

bye

**Comment by HondaRulez** [comment]
Hi,

Perfect thank you :), now works fine on Ubuntu Mate too.

just one more question...
Waht about the versioning ? after "git pull" and Build the package version still be at 150 but the DLL version is 210

![kepernyofoto 2017-08-03 - 7 41 11](https://user-images.githubusercontent.com/12637942/28907634-66461004-781f-11e7-9dda-b2adddc4cea1.png)
