### ISSUE TITLE
stricmp undefined.

### ISSUE THREAD

**Issue by HondaRulez** [podonoghue/usbdm-eclipse-makefiles-build#4]
to be compiling with GCC 5.4 under linux the "stricmp" must be replyced by "strcasecmp"

in files DeviceDatabase_DLL/
src/DeviceData.cpp:829:42: error: ‘stricmp’ was not declared in this scope
src/DeviceData.cpp:851:42: error: ‘stricmp’ was not declared in this scope

src/DeviceXmlParser.cpp:933:64: error: ‘stricmp’ was not declared in this scope
src/DeviceXmlParser.cpp:996:64: error: ‘stricmp’ was not declared in this scope

**Comment by podonoghue** [comment]
Hi HondaRulez,

The Linux version tend to get out of date wrt windows where I do most development.
I have updated the files to build on Linux (Mint).

bye
